function cors(res){
  res.setHeader('Access-Control-Allow-Origin','*');
  res.setHeader('Access-Control-Allow-Methods','POST,DELETE,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers','Content-Type');
}
async function pf(path,opts={}){
  const token=process.env.PRINTIFY_API_TOKEN,shopId=process.env.PRINTIFY_SHOP_ID;
  if(!token) throw new Error('PRINTIFY_API_TOKEN is not configured on the server');
  if(!shopId) throw new Error('PRINTIFY_SHOP_ID is not configured on the server');
  const r=await fetch(`https://api.printify.com/v1/shops/${encodeURIComponent(shopId)}/${path}`,{
    ...opts,headers:{Authorization:`Bearer ${token}`,Accept:'application/json','Content-Type':'application/json','User-Agent':'DTF-Studio-Printify-Bridge/2.0',...(opts.headers||{})}
  });
  const text=await r.text(); let data={}; try{data=text?JSON.parse(text):{}}catch{data={raw:text}}
  if(!r.ok){const err=new Error('Printify API request failed'); err.status=r.status; err.details=data; throw err}
  return data;
}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
module.exports=async function handler(req,res){
  cors(res);
  if(req.method==='OPTIONS') return res.status(204).end();
  try{
    if(req.method==='DELETE'){
      const productId=String(req.query?.productId||'').trim();
      if(!productId) return res.status(400).json({ok:false,error:'productId is required'});
      await pf(`products/${encodeURIComponent(productId)}.json`,{method:'DELETE'});
      return res.status(200).json({ok:true,deleted:true,productId});
    }
    if(req.method!=='POST') return res.status(405).json({ok:false,error:'Method not allowed'});
    const b=req.body||{};
    const blueprintId=Number(b.blueprintId),printProviderId=Number(b.printProviderId),variantId=Number(b.variantId);
    const imageId=String(b.imageId||'').trim(),position=String(b.position||'front').trim();
    const x=Number.isFinite(Number(b.x))?Number(b.x):0.5;
    const y=Number.isFinite(Number(b.y))?Number(b.y):0.5;
    const scale=Math.max(0.01,Number.isFinite(Number(b.scale))?Number(b.scale):0.8);
    const angle=Number.isFinite(Number(b.angle))?Number(b.angle):0;
    if(!blueprintId||!printProviderId||!variantId||!imageId) return res.status(400).json({ok:false,error:'blueprintId, printProviderId, variantId and imageId are required'});
    const payload={
      title:`DTF Studio Preview ${Date.now()}`,
      description:'Temporary unpublished product generated by DTF Studio for a customer mockup preview.',
      blueprint_id:blueprintId,
      print_provider_id:printProviderId,
      variants:[{id:variantId,price:999,is_enabled:true}],
      print_areas:[{variant_ids:[variantId],placeholders:[{position,images:[{id:imageId,x,y,scale,angle}]}]}]
    };
    let product=await pf('products.json',{method:'POST',body:JSON.stringify(payload)});
    for(let i=0;i<4 && (!Array.isArray(product.images)||!product.images.length);i++){
      await sleep(800);
      product=await pf(`products/${encodeURIComponent(product.id)}.json`,{method:'GET'});
    }
    return res.status(200).json({
      ok:true,source:'printify-real-product-mockups',productId:product.id,
      images:Array.isArray(product.images)?product.images:[],
      variants:Array.isArray(product.variants)?product.variants:[],
      printAreas:Array.isArray(product.print_areas)?product.print_areas:[],
      visible:product.visible??null
    });
  }catch(e){
    return res.status(e.status||500).json({ok:false,error:e.message||'Printify request failed',details:e.details||null});
  }
};